# We could use `@actions-rs/cargo` Action ability to automatically install `cross` tool
# in order to compile our application for some unusual targets.

on: [push, pull_request]

name: Cross-compile

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-linux-android
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target=${{ matrix.target }}

  apple:
    name: Apple Build
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - target: aarch64-apple-ios
            tier3: false
          - target: aarch64-apple-watchos
            tier3: true
          - target: aarch64-apple-tvos
            tier3: true
          - target: aarch64-apple-visionos
            tier3: true
        target:
          - aarch64-apple-ios
          - aarch64-apple-watchos
          - aarch64-apple-tvos
          - aarch64-apple-visionos
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.tier3 ?? 'nightly' || 'stable' }}
          target: ${{ matrix.target }}
          override: true
          components: rust-src

      - uses: Build
        run: cargo build --target ${{ matrix.target }} ${{ matrix.tier3 ?? '-Zbuild-std' : '' }}
